[crawler]
timeout = 30
delay_second = 2
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"

[crawler.opgg.aram_augment]
base_url = "https://lol-api-champion.op.gg/api/contents/stats/champions/{0}/aram-augments"
save_directory = "opgg/aram_augments/"
# 可以添加更多URL配置

[crawler.ddragon.champion]
base_url = "https://ddragon.leagueoflegends.com/cdn/{0}/data/en_US/champion.json"
save_directory = "ddragon/champions/"

[suggest]
immediate_select_weighted_sum_threshold = 0.6
immediate_select_precentage_threshold = 0.15
consider_select_weighted_sum_threshold = 0.45
consider_select_precentage_threshold = 0.3